apiVersion: v1
kind: ServiceAccount
metadata:
  name: hasbase-sa
---
# clusterrolebinding 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hasbase-crb
subjects:
- kind: ServiceAccount
  name: hasbase-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# secret
apiVersion: v1
kind: Secret
metadata:
  name: hasbase-sa-secret
  annotations:
    kubernetes.io/service-account.name: hasbase-sa
type: kubernetes.io/service-account-token
---
